[package]
name = "sold"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12"
atty = "0.2"
clap = { version = "3.2.*", features = [ "derive" ] }
failure = "0.1"
lazy_static = "1.4"
once_cell = "1.10"
serde = { features = [ "derive" ], version = "1.0" }
serde_json = "1.0"

ton_abi = { git = 'https://github.com/tonlabs/ton-labs-abi.git', tag = '2.2.8' }
ton_block = { git = 'https://github.com/tonlabs/ton-labs-block.git', tag = '1.7.51' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types.git', tag = '1.11.2' }
tvm_linker = { git = 'https://github.com/tonlabs/TVM-linker.git', branch = 'SilkovAlexander/sold_to_tonos' }

[build-dependencies]
bindgen = "0.59"
cmake = "0.1"

[dev-dependencies]
assert_cmd = "1.0.3"
predicates = "1"

[lib]
name = 'sold_lib'
path = 'src/lib.rs'

[[bin]]
name = "sold"
path = "src/main.rs"